### ISSUE TITLE
Kern y,

### ISSUE THREAD

**Issue by davelab6** [impallari/Raleway#1]
I suggest kerning y,

![screen shot 2016-02-03 at 14 58 03](https://cloud.githubusercontent.com/assets/261579/12795112/8f670a76-ca86-11e5-9e67-b3b7881025d0.png) ![screen shot 2016-02-03 at 14 58 34](https://cloud.githubusercontent.com/assets/261579/12795113/8f681312-ca86-11e5-94ff-6f1a80fe8d64.png) ![screen shot 2016-02-03 at 14 58 25](https://cloud.githubusercontent.com/assets/261579/12795114/8f67c6d2-ca86-11e5-961d-961e4655494a.png)

**Comment by impallari** [comment]
Done
