### ISSUE TITLE
Æ Ø Å / small caps are missing.

### ISSUE THREAD

**Issue by m4ds** [impallari/Raleway#10]
Æ Ø Å / small caps are missing.
![screen shot 2016-09-12 at 12 43 23](https://cloud.githubusercontent.com/assets/12480223/18433199/9818a9cc-78e6-11e6-85b8-a1c25c1439d9.png)

**Comment by impallari** [comment]
We don't fully support Small Caps yet, only the basic A-Z by the moment just as an extra.
