### ISSUE TITLE
Kern non-ligated ligature sequences

### ISSUE THREAD

**Issue by davelab6** [impallari/Raleway#14]
![screen shot 2016-11-02 at 16 16 51](https://cloud.githubusercontent.com/assets/261579/19945737/d4d05320-a117-11e6-9bfd-e002492531a3.png)
![screen shot 2016-11-02 at 16 16 47](https://cloud.githubusercontent.com/assets/261579/19945736/d4cca360-a117-11e6-915e-c47bb478acab.png)

I think you should kern non-ligated ligature sequences.

**Comment by impallari** [comment]
I guess you are looking at the Raleway version used in Lasee's specimenMd tool.
Those are not my raleways files... and they have even bigger kerning issues.
![screen shot 2016-11-03 at 15 53 52](https://cloud.githubusercontent.com/assets/3036973/19980685/c86ea926-a1dd-11e6-9a22-fa46edf5f376.png)
![screen shot 2016-11-03 at 15 09 26](https://cloud.githubusercontent.com/assets/3036973/19980684/c86bff00-a1dd-11e6-92a7-07896742f738.png)
![screen shot 2016-11-03 at 15 09 17](https://cloud.githubusercontent.com/assets/3036973/19980686/c879358a-a1dd-11e6-8fed-7ef4813a8672.png)
![screen shot 2016-11-03 at 15 53 57](https://cloud.githubusercontent.com/assets/3036973/19980687/c87a830e-a1dd-11e6-8788-753103fa5381.png)

**Comment by davelab6** [comment]
Yes I was :) Thanks!
