### ISSUE TITLE
Small italic cyrillic letter "ю" is messed up

### ISSUE THREAD

**Issue by Nekto-github** [impallari/Raleway#15]
![21321323](https://cloud.githubusercontent.com/assets/8641990/20219922/8973d100-a83c-11e6-9cf2-251f09833c8b.png)
raleway v4012

**Comment by impallari** [comment]
Hi Nekto, Thanks for reporting. version 4 is still a work in progress, version 3.001 is the latest stable version.
@alexeiva will fix it.

**Comment by alexeiva** [comment]
@Nekto-github thank you for reporting. This interpolation issue will be fixed in the next w-i-p update.

**Comment by Nekto-github** [comment]
Hey guys, respect for your work. Raleway is my favorite font, and I've made it a main font in several brands I've created. I'm amazed why it's even free - moved to this font after Proxima Nova due to proxima's horrible web-optimization (looked crappy in documents and web-pages). Great job, keep it on.

**Comment by alexeiva** [comment]
Thank you @Nekto-github!

**Comment by Nekto-github** [comment]
Hey guys! Checked out v4020 - it still has that letter broken

**Comment by impallari** [comment]
Yes, it is. In v4020 i've worked on the latin.
Alexei is working in Cyr in his fork. We will merge soon and let you know.

**Comment by alexeiva** [comment]
Issue was not fixed because my previous PR was not merged. 

Here is a new one: https://github.com/impallari/Raleway/pull/18

Note this is currently a development version.

**Comment by Nekto-github** [comment]
@alexeiva 
Hi! Do you mean that there is already a version of Raleway with this issue fixed but it's not yet implemented in the files? If so, I didn't understand how to download this fixed version (sorry for dumb question lol, I'm new to github, never used it). Would appreciate it if you provide a direct link :) I'm currently developing a russian brand with this beautiful font and a fixed version would come handy :)

**Comment by alexeiva** [comment]
@Nekto-github скачать пре-релиз можно [отсюда](https://github.com/cyrealtype/Raleway/releases/tag/4.020)

**Comment by Nekto-github** [comment]
@alexeiva 
Спасибо! Письмо-уведомление о вашем сообщении попало в спам почему-то, не сразу заметил. Божественный фонт, адский респект :)

**Comment by Nekto-github** [comment]
@impallari 
@alexeiva 

Sorry to bother you guys, but I'm just so excited and can't wait: when do you plan to update the major font? So like people could fetch all language subsets right from google fonts, for example, or just download the official stable version named just "Raleway" (not "Raleway v4xxx") and have all these cool updates? :) Just curious, no pressure!

**Comment by alexeiva** [comment]
@Nekto-github 
We cannot comment on GF release dates. Nor do we update the fonts on their servers. 
If you need to use this version for web right away, use a generator, such as http://transfonter.org/

**Comment by Nekto-github** [comment]
@alexeiva 
no-no-no, I don't  mean that I care for Google fonts.

Проще по-русски сказать. Я интересовался, когда все изменения в шрифте выйдут в официальный релиз? :) То есть, если сейчас установить последнюю стабильную официальную версию - там не будет кириллицы в Italic. А если устанавливать версии из WIP, то в системе будет несколько шрифтов - Raleway, Raleway v4012, Raleway v4020 и т.п.  :) Скоро буду менять шрифты в макетах, та еще заморочка лол (с 4012 перейду на 4020, большое спасибо за ссылочку кстати), может тогда подскажете - как поменять имя шрифта, чтоб в систему он вставал под именем Raleway (без v4xxx) и соответственно перезаписывал одноименные файлы - буду очень признателен!

Еще раз спасибо за ваш труд, это лучший шрифт всех времен и народов, у него великое будущее :)
