### ISSUE TITLE
Alternate character for W

### ISSUE THREAD

**Issue by dom1n1k** [impallari/Raleway#17]
Small idea/suggestion: alternate version of 'W' with 3 apexes (instead 4)
I understand that this feature, but sometimes its not very appropriate
Thanks for the great typeface

**Comment by impallari** [comment]
We already have it...

**Comment by Nath007** [comment]
Hi!
I love this font and would like to use it for my website.
I'd like to use the alternate version of "W" too. How can I select this version with css?
I suppose I have to use "font-variant-alternates" but I don't know which parameters I need.
Thank you very much for your help!

**Comment by dom1n1k** [comment]
For v4020 I found:
```
font-feature-settings: "ss02";  /* alternate a */
font-feature-settings: "ss07";  /* alternate t */ 
font-feature-settings: "ss09";  /* alternate W/w */ 
```

**Comment by Nath007** [comment]
Thank you for your answer but I can't make it work. I tried several syntaxes:
    font-feature-settings: "ss09";  /* alternate W/w */
    -webkit-font-feature-settings: "ss09";
    -moz-font-feature-settings: "ss09";
    font-variant-alternates: styleset(ss09);
    -webkit-font-variant-alternates: styleset(ss09);
    -moz-font-variant-alternates: styleset(ss09);
and it doesn't make a difference: it's always the W with 4 apexes.
Have you got any idea?

**Comment by dom1n1k** [comment]
I tried this options for fonts installed to OS (downloaded from this repo) - works fine.
If you load fonts from service like Google Fonts (or similar), it could delete OpenType option for reducing file size. Or you have older version...
