### ISSUE TITLE
Cyrillic lowercase ю is defective in some of the styles (Version 4)

### ISSUE THREAD

**Issue by cssobral2013** [impallari/Raleway#25]

**Comment by davelab6** [comment]
@alexeiva thoughts?

**Comment by alexeiva** [comment]
/ю has been fixed in https://github.com/impallari/Raleway/pull/18 one year
ago. Hope it will be updated faster.

4 янв. 2018 г. 1:52 ДП пользователь "Dave Crossland" <
notifications@github.com> написал:
