### ISSUE TITLE
Best Raleway version to distribute?

### ISSUE THREAD

**Issue by nim-nim** [impallari/Raleway#37]
Hi,

I’m taking over the distribution of Raleway in Fedora Linux. We have many international users, including Cyrillic and Vietnamese speakers.

Therefore, I’d like to have some upstream guidance on the version we should distribute. 3.xxx ? 4.xxx? @alexeiva‘s version ?  An overlay (3.xxx for all scripts, except some that use 4.xxx) ?

Will use of 4.xxx degrade the situation for non Vietnamese/Cyrillic writers? Are non Vietnamese/Cyrillic glyphs worse in 4.xxx?

It sucks to have Cyrillic and Vietnamese stuck in neitherland

**Comment by alexeiva** [comment]
Why not just use my version everywhere?

> Will use of 4.xxx degrade the situation for non Vietnamese/Cyrillic writers? Are non Vietnamese/Cyrillic glyphs worse in 4.xxx?

They are the same

**Comment by nim-nim** [comment]
Hi @alexeiva 

I was just trying to understand the project status, and what was keeping 4.xxx in WIP state since 2016.

Given what you wrote, there is no reason to keep shipping 3.xxx when it is suboptimal for a large part of our userbase. So, I made the switch in our future branch

https://koji.fedoraproject.org/koji/packageinfo?packageID=24044

(meaning a GA this autumn, since it’s a few weeks too late for the summer release feature freeze deadline)

Thank you again for the clarifications!

**Comment by thlinard** [comment]
Hi @nim-nim 
The last development branch is now here:
https://github.com/TypeNetwork/Raleway

Soon to be released, I believe (to be confirmed).

**Comment by nim-nim** [comment]
@thlinard Thanks for the pointer, I check it once in a while to see if it’s alive

**Comment by thlinard** [comment]
Hi @nim-nim 

Now integrated in Google Fonts: https://github.com/google/fonts/pull/2483
