### ISSUE TITLE
Bold fonts are missing

### ISSUE THREAD

**Issue by szedar7** [impallari/Raleway#4]
Not sure if github is related to google font issue but bold fonts are missing: https://www.google.com/fonts/specimen/Raleway

**Comment by szedar7** [comment]
Hmm... Just tested in FF and all seems fine there. In my second PC all looks fine so one machine in chrome (so seems my individual problem)
![image](https://cloud.githubusercontent.com/assets/17587767/13489207/0469b3f4-e126-11e5-8fa8-b6d6d3840aac.png)

I've tried chrome in incognito mode and hard refresh a milion times but still same. Font appear as not bold also on websites I use the font weight 800.

I will leave it open for a while just in case someone else would experience the issue,

**Comment by impallari** [comment]
You may have a cache problem, or maybe you have duplicated installed, or something like that...
