### ISSUE TITLE
Google Fonts weight error.

### ISSUE THREAD

**Issue by mrkubodesign** [impallari/Raleway#5]
Raleway is a beautiful font, however the non-italic versions of the font on [**Google Fonts**](https://www.google.com/fonts/specimen/Raleway) are all Ultra-Bold 900 font weight except the 700 Bold version, and I don't think it should be like that.

I can't seem to find any help on this, and there are a couple of websites like [**Interactive Brokers**](https://www.interactivebrokers.com/en/home.php) who are using the font, and the Ultra-Bold 900 makes it almost unreadable.

**Comment by davelab6** [comment]
Uninstall the font and it should be fixed. Its a chrome bug.

**Comment by mrkubodesign** [comment]
Thank you very much!
